version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres_database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: .
    env_file:
      - .env
    container_name: school_management_backend
    command: >
      sh -c "python manage.py collectstatic --no-input &&
            python manage.py migrate &&
            gunicorn school_management.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
