# Generated by Django 3.2.7 on 2021-10-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='type',
            new_name='address_type',
        ),
    ]
