# Generated by Django 3.2.7 on 2022-03-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20220327_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='students',
            field=models.ManyToManyField(related_name='teachers', to='account.StudentProfile'),
        ),
    ]
