# Generated by Django 4.1 on 2022-08-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_studentprofile_user_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
    ]
