# Generated by Django 3.2.7 on 2022-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule', models.DateTimeField()),
                ('course', models.CharField(blank=True, max_length=100)),
                ('grade_level', models.CharField(blank=True, choices=[('elementary_grade_1', 'Elementary Grade 1'), ('elementary_grade_2', 'Elementary Grade 2'), ('junior_high_school_grade_7', 'Junior High School Grade 7'), ('senior_high_school_grade_11', 'Senior High School Grade 11')], max_length=50)),
            ],
        ),
    ]
